### ISSUE TITLE
How to setup Docker Environment?

### ISSUE THREAD

**Issue by sabipu** [lyzs90/vuewp#7]
I am new with docker and don't know how to setup docker environment. Can you please explain steps to setup docker environment?

Or is it possible to replace Docker with Mamp or something similar ?

**Comment by lyzs90** [comment]
Hey @sabipu sorry for the late response.

Sure can also swap it out for mamp. Just update the environment variables accordingly in the `.env` file i.e. localhost:3306 for the db and localhost:8888 for wordpress

Installing WordPress on mamp:
https://codex.wordpress.org/Installing_WordPress_Locally_on_Your_Mac_With_MAMP
